name: Delivery
on:
  workflow_dispatch:
jobs:
  delivery:
    name: OSSRH Delivery
    runs-on: macos-12
    strategy:
      matrix:
        project: [ types-internal, types, types-kotlinx-serialization ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Deliver all publications
        run: ./gradlew :$PROJECT:publishAllPublicationsToOSSRHRepository
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PROJECT: ${{ matrix.project }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
