name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.api'
      - '**.kt'
      - '**.kts'
      - .github/workflows/integration.yml
      - gradle/**
      - gradle.properties
      - gradlew
      - gradlew.bat
      - yarn.lock
  push:
    branches: [ main ]
    paths:
      - '**.api'
      - '**.kt'
      - '**.kts'
      - .github/workflows/integration.yml
      - gradle/**
      - gradle.properties
      - gradlew
      - gradlew.bat
      - yarn.lock
  workflow_dispatch:
jobs:
  checks:
    name: Checks
    runs-on: macos-12
    strategy:
      matrix:
        project: [ plugins, types-internal, types, types-kotlinx-serialization ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3.5.0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-home-cache-cleanup: true
      - name: Run all checks
        run: ./gradlew :$PROJECT:check
        env:
          PROJECT: ${{ matrix.project }}
